minecraft_version: '1.20.1'
plugins:
  essentials_x:
    - EssentialsX
    - EssentialsXChat
    - EssentialsXGeoIP
    - EssentialsXSpawn

  other:
    chest_cleaner:
      name: 'Chest Cleaner'
      source: 'spigot'
      id: 40313
    core_protect:
      name: 'Core Protect'
      source: 'spigot'
      id: 8631
    g_sit:
      name: 'GSit'
      source: 'spigot'
      id: 62325
    harbor:
      name: 'Harbor'
      source: 'spigot'
      id: 60088
    image_on_map:
      name: 'ImageOnMap'
      source: 'spigot'
      id: 26585
    luck_perms:
      name: 'LuckPerms'
      source: 'spigot'
      id: 28140
    multiverse_core:
      name: 'Multiverse-Core'
      source: 'spigot'
      id: 390
    vault:
      name: 'Vault'
      source: 'spigot'
      id: 34315