minecraft_version: '1.20.4'
mod_loader: 'paper'
mods:
  modrinth:
    - create
plugins:
  essentials_x:
    - 'EssentialsX'
    - 'EssentialsXChat'
    - 'EssentialsXGeoIP'
    - 'EssentialsXSpawn'

  spigot:
    - 62325

  modrinth:
    - mapify